cloud:
  aws:
    region:
      static: regionOfSqsQueueHere
      auto: false
    stack:
      auto: false
    credentials:
      access-key: accessKeyHere
      secret-key: secretKeyHere
    end-point:
      url: sqsStandardQueueUrlHere
